@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package dev.xkmc.fastprojectileapi.spellcircle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;