@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package dev.xkmc.youkaishomecoming.compat.touhoulittlemaid;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;